#spring:
#  application:
#    name: eureka-server
#server:
#  port: 8000
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    # 是否从eureka-server中获取注册信息
#    # 默认为true(多节点)单节点不需要同步其他节点数据
#    fetch-registry: false
#    # 默认为true(多节点) 是否将自己注册到eureka-server中
#    register-with-eureka: false
#    # eureka-server 所在地址
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
